name: Qt CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QT_VERSION: '5.15.2'

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qt5-qmake \
            qtbase5-dev \
            xvfb

      - name: Build
        run: |
          qmake advanced_tic_tac_toe.pro
          make -j$(nproc)

      - name: Test
        timeout-minutes: 2
        run: |
          xvfb-run --auto-servernum \
            ./advanced_tic_tac_toe \
            --ci-mode \
            --test-timeout 10000

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: advanced_tic_tac_toe