name: Qt/C++ CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: تحميل الكود المصدري
      - uses: actions/checkout@v4

      # الخطوة 2: تثبيت المتطلبات الأساسية
      - name: Install Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qt5-qmake \
            qtbase5-dev \
            g++ \
            make \
            xvfb

      # الخطوة 3: بناء المشروع
      - name: Build Project
        run: |
          qmake advanced_tic_tac_toe.pro
          make

      # الخطوة 4: اختبار التطبيق مع Xvfb (للنوافذ الرسومية)
      - name: Run Application with Virtual Display
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" ./advanced_tic_tac_toe

      # الخطوة 5: (اختياري) حزمة التطبيق للنشر
      - name: Package Application
        run: |
          mkdir -p package
          cp advanced_tic_tac_toe package/
          tar -czvf app-release.tar.gz package/