name: Qt CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    # الخطوة 1: تحميل الكود
    - uses: actions/checkout@v4

    # الخطوة 2: تثبيت Qt والمتطلبات
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          qt5-qmake \
          qtbase5-dev \
          libgl1-mesa-dev \
          xvfb

    # الخطوة 3: البناء
    - name: Build
      run: |
        qmake advanced_tic_tac_toe.pro
        make -j$(nproc)

    # الخطوة 4: الاختبار (مع إغلاق تلقائي)
    - name: Test
      timeout-minutes: 2
      run: |
        xvfb-run --auto-servernum \
          ./advanced_tic_tac_toe \
          --ci-mode \
          --test-timeout 10000  # 10 ثواني