name: Qt CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Cache Qt
        uses: actions/cache@v3
        with:
          path: /usr/local/Qt
          key: ${{ runner.os }}-qt-${{ hashFiles('advanced_tic_tac_toe.pro') }}

      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qt5-qmake \
            qtbase5-dev \
            xvfb

      - name: Build
        run: |
          qmake advanced_tic_tac_toe.pro
          make -j$(nproc)

      - name: Test
        timeout-minutes: 2
        run: |
          xvfb-run --auto-servernum \
            ./advanced_tic_tac_toe \
            --ci-mode \
            --test-timeout 15000  # 15 ثانية

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: advanced_tic_tac_toe
          
              - name: Run Unit Tests
      run: |
        g++ tests/test_gamelogic.cpp src/gamelogic.cpp -I./src -o test_gamelogic
        ./test_gamelogic
