name: Qt CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt and build tools
        run: |
          sudo apt update
          sudo apt install -y qtbase5-dev qt5-qmake g++ make xvfb

      - name: Build project with qmake
        run: |
          qmake advanced_tic_tac_toe.pro
          make -j$(nproc)

      - name: Run unit test
        run: |
          g++ test/test_gamelogic.cpp gamelogic.cpp -o test_gamelogic
          ./test_gamelogic

      - name: Upload executable
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tic_tac_toe_exe
          path: ./advanced_tic_tac_toe
