name: Qt CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt and build tools
        run: |
          sudo apt update
          sudo apt install -y qtbase5-dev qt5-qmake g++ make xvfb

      - name: Build project with qmake
        run: |
          qmake advanced_tic_tac_toe.pro
          make -j$(nproc)

      - name: Run unit test
        run: |
          g++ test/test_gamelogic.cpp gamelogic.cpp -o test_gamelogic
          ./test_gamelogic

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0
          name: "v1.0 Release"
          body: |
            🎉 First official release of Advanced Tic Tac Toe!
            - Includes AI with multiple difficulty levels
            - Player vs Player & AI
            - Login & History system
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Executable to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./advanced_tic_tac_toe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
