name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Qt
      run: |
        sudo apt update
        sudo apt install -y qt5-default qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools g++ make

    - name: Build Project
      run: |
        qmake
        make
