name: Qt/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - uses: actions/checkout@v4
    
    # Install Qt and build dependencies
    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev g++ make
        
    # Build the project
    - name: Build with qmake
      run: |
        qmake advanced_tic_tac_toe.pro
        make
        
    # Optional: Run tests if you have them
    - name: Run tests
      run: |
        ./advanced_tic_tac_toe  # Replace with your test command if available