name: Qt CI Pipeline
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Cache Qt
        uses: actions/cache@v3
        with:
          path: /usr/local/Qt
          key: ${{ runner.os }}-qt-${{ hashFiles('advanced_tic_tac_toe.pro', '.github/workflows/build.yml') }}
      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-tools-dev qt6-tools-dev-tools qtcreator g++ make xvfb libqt6widgets6
      - name: Build
        run: |
          qmake advanced_tic_tac_toe.pro
          make -j$(nproc)
      - name: Run App for CI (Optional)
        if: env.CI_MODE != 'skip'
        run: |
          xvfb-run --auto-servernum ./advanced_tic_tac_toe --ci-mode --test-timeout 15000
      - name: Run Unit Tests
        run: |
          qmake test/test_gamelogic.pro
          make -j$(nproc)
          ./test_gamelogic
      - name: Upload Executable (Optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: advanced_tic_tac_toe